// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz5YVWSm_yKJnvmS8hPAuUpeULZCCWY5k',
    appId: '1:790295269125:web:4fee0351eba7637dbd716c',
    messagingSenderId: '790295269125',
    projectId: 'quickattend-6608f',
    authDomain: 'quickattend-6608f.firebaseapp.com',
    storageBucket: 'quickattend-6608f.appspot.com',
    measurementId: 'G-Y0MRGNYJFJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATKMuNlWnFOoAVGMr8JmG1xyQJ47HJ2BM',
    appId: '1:790295269125:android:440353a6605e9ec7bd716c',
    messagingSenderId: '790295269125',
    projectId: 'quickattend-6608f',
    storageBucket: 'quickattend-6608f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjUrOSE9tm4lykf5XZVopHWzUbYqEHYUk',
    appId: '1:790295269125:ios:a46ea07bc3a87984bd716c',
    messagingSenderId: '790295269125',
    projectId: 'quickattend-6608f',
    storageBucket: 'quickattend-6608f.appspot.com',
    iosBundleId: 'com.yashmistry.quickAttend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjUrOSE9tm4lykf5XZVopHWzUbYqEHYUk',
    appId: '1:790295269125:ios:a46ea07bc3a87984bd716c',
    messagingSenderId: '790295269125',
    projectId: 'quickattend-6608f',
    storageBucket: 'quickattend-6608f.appspot.com',
    iosBundleId: 'com.yashmistry.quickAttend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCz5YVWSm_yKJnvmS8hPAuUpeULZCCWY5k',
    appId: '1:790295269125:web:89889be952454247bd716c',
    messagingSenderId: '790295269125',
    projectId: 'quickattend-6608f',
    authDomain: 'quickattend-6608f.firebaseapp.com',
    storageBucket: 'quickattend-6608f.appspot.com',
    measurementId: 'G-XMEMDDRTMP',
  );
}
